name: Run Seans Bot Hourly

on:
  schedule:
    - cron: "0 * * * *"  # Her saat başı (UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 python-telegram-bot==13.15

      - name: Run bot
        env:
          TC: ${{ secrets.TC }}
          SIFRE: ${{ secrets.SIFRE }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python seans_bot.py
